/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as BareRouteImport } from './routes/_bare';
import { Route as BareWpAdminRouteImport } from './routes/_bare.wp-admin';
import { Route as DefaultRouteImport } from './routes/_default';
import { Route as DefaultAboutRouteImport } from './routes/_default.about';
import { Route as DefaultAttributionsRouteImport } from './routes/_default.attributions';
import { Route as DefaultIndexRouteImport } from './routes/_default.index';
import { Route as DefaultPoliciesCookiesPolicyRouteImport } from './routes/_default.policies.cookies-policy';
import { Route as DefaultPoliciesIndexRouteImport } from './routes/_default.policies.index';
import { Route as DefaultPoliciesPrivacyPolicyRouteImport } from './routes/_default.policies.privacy-policy';

const BareRoute = BareRouteImport.update({
  id: '/_bare',
  getParentRoute: () => rootRouteImport,
} as any);
const DefaultRoute = DefaultRouteImport.update({
  id: '/_default',
  getParentRoute: () => rootRouteImport,
} as any);
const BareWpAdminRoute = BareWpAdminRouteImport.update({
  id: '/wp-admin',
  path: '/wp-admin',
  getParentRoute: () => BareRoute,
} as any);
const DefaultIndexRoute = DefaultIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DefaultRoute,
} as any);
const DefaultAboutRoute = DefaultAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => DefaultRoute,
} as any);
const DefaultAttributionsRoute = DefaultAttributionsRouteImport.update({
  id: '/attributions',
  path: '/attributions',
  getParentRoute: () => DefaultRoute,
} as any);
const DefaultPoliciesIndexRoute = DefaultPoliciesIndexRouteImport.update({
  id: '/policies/',
  path: '/policies/',
  getParentRoute: () => DefaultRoute,
} as any);
const DefaultPoliciesCookiesPolicyRoute =
  DefaultPoliciesCookiesPolicyRouteImport.update({
    id: '/policies/cookies-policy',
    path: '/policies/cookies-policy',
    getParentRoute: () => DefaultRoute,
  } as any);
const DefaultPoliciesPrivacyPolicyRoute =
  DefaultPoliciesPrivacyPolicyRouteImport.update({
    id: '/policies/privacy-policy',
    path: '/policies/privacy-policy',
    getParentRoute: () => DefaultRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof DefaultIndexRoute;
  '/wp-admin': typeof BareWpAdminRoute;
  '/about': typeof DefaultAboutRoute;
  '/attributions': typeof DefaultAttributionsRoute;
  '/policies/cookies-policy': typeof DefaultPoliciesCookiesPolicyRoute;
  '/policies/privacy-policy': typeof DefaultPoliciesPrivacyPolicyRoute;
  '/policies/': typeof DefaultPoliciesIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof DefaultIndexRoute;
  '/wp-admin': typeof BareWpAdminRoute;
  '/about': typeof DefaultAboutRoute;
  '/attributions': typeof DefaultAttributionsRoute;
  '/policies/cookies-policy': typeof DefaultPoliciesCookiesPolicyRoute;
  '/policies/privacy-policy': typeof DefaultPoliciesPrivacyPolicyRoute;
  '/policies': typeof DefaultPoliciesIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_bare': typeof BareRouteWithChildren;
  '/_default': typeof DefaultRouteWithChildren;
  '/_bare/wp-admin': typeof BareWpAdminRoute;
  '/_default/about': typeof DefaultAboutRoute;
  '/_default/attributions': typeof DefaultAttributionsRoute;
  '/_default/': typeof DefaultIndexRoute;
  '/_default/policies/cookies-policy': typeof DefaultPoliciesCookiesPolicyRoute;
  '/_default/policies/privacy-policy': typeof DefaultPoliciesPrivacyPolicyRoute;
  '/_default/policies/': typeof DefaultPoliciesIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/wp-admin'
    | '/about'
    | '/attributions'
    | '/policies/cookies-policy'
    | '/policies/privacy-policy'
    | '/policies/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/wp-admin'
    | '/about'
    | '/attributions'
    | '/policies/cookies-policy'
    | '/policies/privacy-policy'
    | '/policies';
  id:
    | '__root__'
    | '/_bare'
    | '/_default'
    | '/_bare/wp-admin'
    | '/_default/about'
    | '/_default/attributions'
    | '/_default/'
    | '/_default/policies/cookies-policy'
    | '/_default/policies/privacy-policy'
    | '/_default/policies/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  BareRoute: typeof BareRouteWithChildren;
  DefaultRoute: typeof DefaultRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_bare': {
      id: '/_bare';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof BareRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_default': {
      id: '/_default';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof DefaultRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_bare/wp-admin': {
      id: '/_bare/wp-admin';
      path: '/wp-admin';
      fullPath: '/wp-admin';
      preLoaderRoute: typeof BareWpAdminRouteImport;
      parentRoute: typeof BareRoute;
    };
    '/_default/': {
      id: '/_default/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof DefaultIndexRouteImport;
      parentRoute: typeof DefaultRoute;
    };
    '/_default/about': {
      id: '/_default/about';
      path: '/about';
      fullPath: '/about';
      preLoaderRoute: typeof DefaultAboutRouteImport;
      parentRoute: typeof DefaultRoute;
    };
    '/_default/attributions': {
      id: '/_default/attributions';
      path: '/attributions';
      fullPath: '/attributions';
      preLoaderRoute: typeof DefaultAttributionsRouteImport;
      parentRoute: typeof DefaultRoute;
    };
    '/_default/policies/': {
      id: '/_default/policies/';
      path: '/policies';
      fullPath: '/policies/';
      preLoaderRoute: typeof DefaultPoliciesIndexRouteImport;
      parentRoute: typeof DefaultRoute;
    };
    '/_default/policies/cookies-policy': {
      id: '/_default/policies/cookies-policy';
      path: '/policies/cookies-policy';
      fullPath: '/policies/cookies-policy';
      preLoaderRoute: typeof DefaultPoliciesCookiesPolicyRouteImport;
      parentRoute: typeof DefaultRoute;
    };
    '/_default/policies/privacy-policy': {
      id: '/_default/policies/privacy-policy';
      path: '/policies/privacy-policy';
      fullPath: '/policies/privacy-policy';
      preLoaderRoute: typeof DefaultPoliciesPrivacyPolicyRouteImport;
      parentRoute: typeof DefaultRoute;
    };
  }
}

interface BareRouteChildren {
  BareWpAdminRoute: typeof BareWpAdminRoute;
}

const BareRouteChildren: BareRouteChildren = {
  BareWpAdminRoute: BareWpAdminRoute,
};

const BareRouteWithChildren = BareRoute._addFileChildren(BareRouteChildren);

interface DefaultRouteChildren {
  DefaultAboutRoute: typeof DefaultAboutRoute;
  DefaultAttributionsRoute: typeof DefaultAttributionsRoute;
  DefaultIndexRoute: typeof DefaultIndexRoute;
  DefaultPoliciesCookiesPolicyRoute: typeof DefaultPoliciesCookiesPolicyRoute;
  DefaultPoliciesPrivacyPolicyRoute: typeof DefaultPoliciesPrivacyPolicyRoute;
  DefaultPoliciesIndexRoute: typeof DefaultPoliciesIndexRoute;
}

const DefaultRouteChildren: DefaultRouteChildren = {
  DefaultAboutRoute: DefaultAboutRoute,
  DefaultAttributionsRoute: DefaultAttributionsRoute,
  DefaultIndexRoute: DefaultIndexRoute,
  DefaultPoliciesCookiesPolicyRoute: DefaultPoliciesCookiesPolicyRoute,
  DefaultPoliciesPrivacyPolicyRoute: DefaultPoliciesPrivacyPolicyRoute,
  DefaultPoliciesIndexRoute: DefaultPoliciesIndexRoute,
};

const DefaultRouteWithChildren =
  DefaultRoute._addFileChildren(DefaultRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  BareRoute: BareRouteWithChildren,
  DefaultRoute: DefaultRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { createStart } from '@tanstack/react-start';
import type { getRouter } from './router.tsx';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
