/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as BareRouteImport } from './routes/_bare';
import { Route as BareWpAdminRouteImport } from './routes/_bare.wp-admin';
import { Route as DefaultRouteImport } from './routes/_default';
import { Route as DefaultIndexRouteImport } from './routes/_default.index';

const BareRoute = BareRouteImport.update({
  id: '/_bare',
  getParentRoute: () => rootRouteImport,
} as any);
const DefaultRoute = DefaultRouteImport.update({
  id: '/_default',
  getParentRoute: () => rootRouteImport,
} as any);
const BareWpAdminRoute = BareWpAdminRouteImport.update({
  id: '/wp-admin',
  path: '/wp-admin',
  getParentRoute: () => BareRoute,
} as any);
const DefaultIndexRoute = DefaultIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DefaultRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof DefaultIndexRoute;
  '/wp-admin': typeof BareWpAdminRoute;
}
export interface FileRoutesByTo {
  '/': typeof DefaultIndexRoute;
  '/wp-admin': typeof BareWpAdminRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_bare': typeof BareRouteWithChildren;
  '/_default': typeof DefaultRouteWithChildren;
  '/_bare/wp-admin': typeof BareWpAdminRoute;
  '/_default/': typeof DefaultIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/wp-admin';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/wp-admin';
  id: '__root__' | '/_bare' | '/_default' | '/_bare/wp-admin' | '/_default/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  BareRoute: typeof BareRouteWithChildren;
  DefaultRoute: typeof DefaultRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_bare': {
      id: '/_bare';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof BareRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_default': {
      id: '/_default';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof DefaultRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_bare/wp-admin': {
      id: '/_bare/wp-admin';
      path: '/wp-admin';
      fullPath: '/wp-admin';
      preLoaderRoute: typeof BareWpAdminRouteImport;
      parentRoute: typeof BareRoute;
    };
    '/_default/': {
      id: '/_default/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof DefaultIndexRouteImport;
      parentRoute: typeof DefaultRoute;
    };
  }
}

interface BareRouteChildren {
  BareWpAdminRoute: typeof BareWpAdminRoute;
}

const BareRouteChildren: BareRouteChildren = {
  BareWpAdminRoute: BareWpAdminRoute,
};

const BareRouteWithChildren = BareRoute._addFileChildren(BareRouteChildren);

interface DefaultRouteChildren {
  DefaultIndexRoute: typeof DefaultIndexRoute;
}

const DefaultRouteChildren: DefaultRouteChildren = {
  DefaultIndexRoute: DefaultIndexRoute,
};

const DefaultRouteWithChildren =
  DefaultRoute._addFileChildren(DefaultRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  BareRoute: BareRouteWithChildren,
  DefaultRoute: DefaultRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { createStart } from '@tanstack/react-start';
import type { getRouter } from './router.tsx';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
