apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: personal-website-tls
  namespace: bernardoforcillo-com
spec:
  secretName: personal-website-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: bernardoforcillo.com
  dnsNames:
    - bernardoforcillo.com
    - www.bernardoforcillo.com
