apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-non-www
  namespace: bernardoforcillo-com
spec:
  redirectRegex:
    regex: "^https://www\\.(.*)"
    replacement: "https://$1"
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-http-to-https
  namespace: bernardoforcillo-com
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: tlsoptions
  namespace: bernardoforcillo-com
spec:
  minVersion: VersionTLS12
  maxVersion: VersionTLS13
  cipherSuites:
    - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    - TLS_AES_256_GCM_SHA384
    - TLS_AES_128_GCM_SHA256
    - TLS_CHACHA20_POLY1305_SHA256
    - TLS_FALLBACK_SCSV
  curvePreferences:
    - X25519        # Modern, secure curve
    - CurveP384     # NIST P-384
    - CurveP521     # NIST P-521
  sniStrict: true   # Enforce SNI matching
  alpnProtocols:
    - h2           # HTTP/2
    - http/1.1     # HTTP/1.1 fallback
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security
  namespace: bernardoforcillo-com
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
    customRequestHeaders:
      X-Forwarded-Proto: "https"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: rate-limit
  namespace: bernardoforcillo-com
spec:
  rateLimit:
    average: 10000
    period: 1s
    burst: 200
    sourceCriterion:
      ipStrategy:
        depth: 1
