apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - commons.yaml
  # Apis website files
  - main/www/deployment.yaml
  - main/www/service.yaml
  - main/www/certificate.yaml
  - main/www/ingress.yaml
